# Generated by Django 5.2.5 on 2025-10-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicaties", "0004_applicatie_applicatie_gebruiker_token_timeout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicatie",
            name="stuur_notificatie_melding_afgesloten",
            field=models.BooleanField(
                default=False,
                help_text="Deze notificatie is alleen van toepassing op signaalapplicaties",
            ),
        ),
        migrations.AddField(
            model_name="applicatie",
            name="stuur_notificatie_melding_veranderd",
            field=models.BooleanField(
                default=False,
                help_text="Deze notificatie is alleen van toepassing op taakapplicaties",
            ),
        ),
    ]
