# Generated by Django 5.2.5 on 2025-11-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "applicaties",
            "0005_applicatie_stuur_notificatie_melding_afgesloten_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicatie",
            name="stuur_notificatie_melding_veranderd",
            field=models.BooleanField(default=False),
        ),
    ]
