# Generated by Django 5.2.5 on 2026-01-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicaties", "0006_alter_applicatie_stuur_notificatie_melding_veranderd"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicatie",
            name="applicatie_auth_header_key",
            field=models.CharField(default="Authorization", max_length=100),
        ),
        migrations.AddField(
            model_name="applicatie",
            name="applicatie_auth_header_token_prefix",
            field=models.CharField(
                blank=True, default="Token", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="applicatie",
            name="applicatie_token_api_path",
            field=models.CharField(default="api-token-auth", max_length=100),
        ),
        migrations.AddField(
            model_name="applicatie",
            name="applicatie_token_retrieve_method",
            field=models.CharField(
                choices=[("post", "POST"), ("get", "GET")],
                default="post",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="applicatie",
            name="notificatie_melding_afgesloten_url_postfix",
            field=models.CharField(
                blank=True, default="melding-afgesloten/", max_length=100, null=True
            ),
        ),
    ]
