version: '3'
services:
  core:
    build: ./core
    extra_hosts:
      - "mor-core.forzamor.local:172.17.0.1"
    ports:
      - "80:8000"
    env_file:
      - .env.local
    volumes:
      - ./core:/app
      - ./media:/media
    depends_on:
      - database
    networks:
      - mor_network
    command: ["bash", "/app/deploy/docker-entrypoint.development.sh"]

  database:
    image: postgis/postgis:11-3.3
    shm_size: '1024m'
    ports:
      - "5410:5433"
    env_file:
      - .env.local
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mor_network

volumes:
  postgres-data:

networks:
  mor_network:
    external: true
