version: "3.5"
services:
  app:
    build: ./app
    ports:
      - 8002:8000
      - 5678:5678
    env_file:
      - .env.test
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_healthy
    links:
      - database
    networks:
      - mor_test_network
    stdin_open: true
    tty: true

  database:
    image: postgis/postgis:11-3.3
    shm_size: '1024m'
    ports:
      - "5433"
    env_file:
      - .env.test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mor_test_network

  redis:
    image: redis
    networks:
      - mor_test_network
    ports:
      - "6379"

networks:
  mor_test_network:
    external: true
