version: '3'
services:
  gateway:
    container_name: core.mor.local
    build: ./nginx
    volumes:
      - ./nginx/nginx-default.development.conf:/etc/nginx/conf.d/default.conf
      - ./media:/media
    depends_on:
      core_app:
        condition: service_started
    ports:
      - 8002:8002
    networks:
      - mor_bridge_network
    env_file:
      - .env.local
  core_app:
    build: ./app
    extra_hosts:
      - "mor-core.forzamor.local:172.17.0.1"
    env_file:
      - .env.local
    volumes:
      - ./app:/app
      - ./media:/media
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - mor_network
      - mor_bridge_network
    command: ["bash", "/app/deploy/docker-entrypoint.development.sh"]

  database:
    image: postgis/postgis:11-3.3
    shm_size: '1024m'
    ports:
      - "7998:5432"
    env_file:
      - .env.local
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mor_network

  redis:
    image: redis
    networks:
      - mor_network
    ports:
      - "6379"

  core_celery_worker:
    build: ./app
    command: "celery -A config worker -l info"
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ./media:/media
    env_file:
      - .env.local
    networks:
      - mor_network
      - mor_bridge_network
    # restart: on-failure

  core_app_celery_beat:
    build: ./app
    command: "celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ./media:/media
    env_file:
      - .env.local
    networks:
      - mor_network
      - mor_bridge_network
    # restart: on-failure

volumes:
  postgres-data:

networks:
  mor_network:
    external: true
  mor_bridge_network:
    external: true
