version: "3.5"
services:
  core:
    build: ./core
    # hostname: core
    # image: core
    ports:
      - 8080:8000
      - 5678:5678
    env_file:
      - .env.test
    # volumes:
    #   - ./core:/app
    #   - ./media:/media
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    networks:
      - mor_network
    stdin_open: true
    tty: true
    # command: ["bash", "/app/deploy/docker-entrypoint.development.sh"]

  database:
    image: postgis/postgis:11-3.3
    shm_size: '1024m'
    ports:
      - "5432:5433"
    env_file:
      - .env.test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mor_network

networks:
  mor_network:
    external: true
