# Generated by Django 4.2.15 on 2025-09-25 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_results", "0014_alter_taskresult_status"),
        ("taken", "0012_alter_taakopdracht_titel"),
    ]

    operations = [
        migrations.AddField(
            model_name="taakopdracht",
            name="task_taak_aanmaken",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taakopdracht",
                to="django_celery_results.taskresult",
            ),
        ),
    ]
