# Generated by Django 5.2.5 on 2025-10-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicaties", "0004_applicatie_applicatie_gebruiker_token_timeout_and_more"),
        ("django_celery_results", "0014_alter_taskresult_status"),
        ("meldingen", "0025_alter_meldinggebeurtenis_gebeurtenis_type"),
        ("taken", "0013_taakopdracht_task_taak_aanmaken"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="taakopdracht",
            index=models.Index(fields=["uuid"], name="taakopdracht_uuid_idx"),
        ),
    ]
