# Generated by Django 5.2.5 on 2025-11-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0014_taakopdracht_taakopdracht_uuid_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="taakopdracht",
            name="taak_aanmaken_error",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
