# Generated by Django 5.2.5 on 2025-11-27 18:04

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0015_taakopdracht_taak_aanmaken_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="taakopdracht",
            name="afhankelijkheid",
            field=utils.fields.ListJSONField(default=list),
        ),
    ]
