# Generated by Django 5.2.5 on 2025-12-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0016_taakopdracht_afhankelijkheid"),
    ]

    operations = [
        migrations.AddField(
            model_name="taakopdracht",
            name="uitgezet_op",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
