# Generated by Django 5.2.5 on 2025-12-16 09:56

from django.db import migrations


def set_uitgezet_op(apps, schema_editor):
    Taakopdracht = apps.get_model("taken", "Taakopdracht")
    for taakopdracht in Taakopdracht.objects.all():
        taakopdracht.uitgezet_op = taakopdracht.aangemaakt_op
        taakopdracht.save()


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0017_taakopdracht_uitgezet_op"),
    ]

    operations = [
        migrations.RunPython(set_uitgezet_op),
    ]
