global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: monitoring
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["host.docker.internal:8080"]
