# Generated by Django 4.2.15 on 2025-02-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bijlagen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bijlage",
            name="minified_op",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
