# Generated by Django 4.2.15 on 2025-04-30 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "locatie",
            "0007_locatie_buurtnaam_wijknaam_idx_locatie_buurtnaam_idx_and_more",
        ),
        ("meldingen", "0018_auto_20241009_1406"),
    ]

    operations = [
        migrations.AddField(
            model_name="melding",
            name="locatie",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="melding_voor_locatie",
                to="locatie.locatie",
            ),
        ),
        migrations.AddField(
            model_name="melding",
            name="onderwerp",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="melding",
            name="zoek_tekst",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
