# Generated by Django 4.2.15 on 2025-05-02 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bijlagen", "0003_bijlage_bestand_hash"),
        ("meldingen", "0019_melding_locatie_melding_onderwerp_melding_zoek_tekst"),
    ]

    operations = [
        migrations.AddField(
            model_name="melding",
            name="bijlage",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="melding_voor_bijlage",
                to="bijlagen.bijlage",
            ),
        ),
    ]
