# Generated by Django 4.2.15 on 2025-05-13 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meldingen", "0021_auto_20250506_1539"),
    ]

    operations = [
        migrations.RenameField(
            model_name="melding",
            old_name="locatie",
            new_name="referentie_locatie",
        ),
        migrations.RenameField(
            model_name="melding",
            old_name="bijlage",
            new_name="thumbnail_afbeelding",
        ),
    ]
