# Generated by Django 4.2.15 on 2025-06-11 11:19

import uuid

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meldingen", "0022_rename_locatie_melding_referentie_locatie_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specificatie",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("naam", models.CharField(max_length=255, unique=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        overwrite=True,
                        populate_from=("naam",),
                        unique=True,
                    ),
                ),
                ("verwijderd_op", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="melding",
            name="afhandelreden",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="meldinggebeurtenis",
            name="afhandelreden",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="meldinggebeurtenis",
            name="resolutie",
            field=models.CharField(
                blank=True,
                choices=[("opgelost", "Opgelost"), ("niet_opgelost", "Niet opgelost")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="melding",
            name="resolutie",
            field=models.CharField(
                blank=True,
                choices=[("opgelost", "Opgelost"), ("niet_opgelost", "Niet opgelost")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="melding",
            name="specificatie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meldingen_voor_specificatie",
                to="meldingen.specificatie",
            ),
        ),
        migrations.AddField(
            model_name="meldinggebeurtenis",
            name="specificatie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meldinggebeurtenissen_voor_specificatie",
                to="meldingen.specificatie",
            ),
        ),
    ]
