# Generated by Django 4.2.15 on 2025-07-03 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meldingen", "0023_specificatie_melding_afhandelreden_and_more"),
    ]

    operations = [
        migrations.RunSQL("DROP VIEW IF EXISTS dwh_meldingen_melding;"),
        migrations.RunSQL(
            """CREATE VIEW dwh_meldingen_melding AS
                SELECT id,
                    uuid,
                    aangemaakt_op,
                    aangepast_op,
                    origineel_aangemaakt,
                    afgesloten_op,
                    meta - 'melderNaamField'::text - 'melderEmailField'::text - 'melderTelefoonField'::text - 'adoptantnummerField'::text AS meta,
                        CASE
                            WHEN (meta ->> 'melderEmailField'::text) ~~* '%@rotterdam.nl'::text THEN 1
                            ELSE 0
                        END AS rotterdam_email,
                        CASE
                            WHEN (meta ->> 'adoptantnummerField'::text) <> '0'::text AND (meta ->> 'adoptantnummerField'::text) <> ''::text THEN 1
                            ELSE 0
                        END AS has_adoptantnummer,
                    (meta ->> 'kanaalField'::text) AS meta__kanaal_field,
                    (meta ->> 'omschrijvingField'::text) AS meta__omschrijving_field,
                    (meta ->> 'meldingsnummerField'::text) AS meta__meldinsgnummer_field,
                    (meta ->> 'aanvullendeInformatieField'::text) AS meta__aanvullende_informatie_field,
                    resolutie,
                    status_id,
                    urgentie,
                    referentie_locatie_id,
                    afhandelreden,
                    specificatie_id
                FROM meldingen_melding
            ;"""
        ),
        migrations.RunSQL("GRANT SELECT ON TABLE dwh_meldingen_melding TO dwh;"),
        migrations.RunSQL(
            "GRANT SELECT ON TABLE dwh_meldingen_melding TO CURRENT_ROLE;"
        ),
        migrations.RunSQL("DROP VIEW IF EXISTS dwh_meldingen_specificatie;"),
        migrations.RunSQL(
            """CREATE VIEW dwh_meldingen_specificatie AS
                SELECT uuid,
                    naam,
                    verwijderd_op,
                    aangemaakt_op,
                    aangepast_op
                FROM meldingen_specificatie
            ;"""
        ),
        migrations.RunSQL("GRANT SELECT ON TABLE dwh_meldingen_specificatie TO dwh;"),
        migrations.RunSQL(
            "GRANT SELECT ON TABLE dwh_meldingen_specificatie TO CURRENT_ROLE;"
        ),
    ]
