# Generated by Django 4.2.15 on 2025-07-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meldingen", "0024_auto_20250703_1639"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meldinggebeurtenis",
            name="gebeurtenis_type",
            field=models.CharField(
                choices=[
                    ("standaard", "Standaard"),
                    ("status_wijziging", "Status wijziging"),
                    ("melding_aangemaakt", "Melding aangemaakt"),
                    ("taakopdracht_aangemaakt", "Taakopdracht aangemaakt"),
                    ("taakopdracht_verwijderd", "Taakopdracht verwijderd"),
                    ("taakopdracht_notificatie", "Taakopdracht notificatie"),
                    ("taakopdracht_status_wijziging", "Taakopdracht status wijziging"),
                    ("locatie_aangemaakt", "Locatie aangemaakt"),
                    ("signaal_toegevoegd", "Signaal toegevoegd"),
                    ("urgentie_aangepast", "Urgentie aangepast"),
                    ("melding_heropend", "Melding heropend"),
                    ("melding_afgehandeld", "Melding afgehandeld"),
                ],
                default="standaard",
                max_length=40,
            ),
        ),
    ]
