# Generated by Django 4.2.15 on 2025-10-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signalen", "0007_alter_signaal_omschrijving_melder"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="signaal",
            index=models.Index(fields=["signaal_url"], name="signaal_url_idx"),
        ),
    ]
