# Generated by Django 5.2.5 on 2025-10-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aliassen", "0002_alter_onderwerpalias_response_json"),
        ("melders", "0001_initial"),
        ("meldingen", "0025_alter_meldinggebeurtenis_gebeurtenis_type"),
        ("signalen", "0008_signaal_signaal_url_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="signaal",
            index=models.Index(fields=["uuid"], name="signaal_uuid_idx"),
        ),
    ]
