# Generated by Django 5.2.5 on 2026-01-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signalen", "0009_signaal_signaal_uuid_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="signaal",
            name="kanaal",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="signaal",
            name="versie",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
