# Generated by Django 4.2.15 on 2025-02-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locatie", "0006_locatie_primair"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="locatie",
            index=models.Index(
                fields=["buurtnaam", "wijknaam"], name="buurtnaam_wijknaam_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locatie",
            index=models.Index(fields=["buurtnaam"], name="buurtnaam_idx"),
        ),
        migrations.AddIndex(
            model_name="locatie",
            index=models.Index(fields=["wijknaam"], name="wijknaam_idx"),
        ),
    ]
