# Generated by Django 4.2.15 on 2025-10-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locatie", "0008_auto_20250506_1412"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locatie",
            name="gebruiker",
        ),
        migrations.AddIndex(
            model_name="locatie",
            index=models.Index(
                fields=["buurtnaam", "wijknaam", "plaatsnaam"],
                name="buurt_wijk_plaats_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="locatie",
            index=models.Index(fields=["plaatsnaam"], name="plaatsnaam_idx"),
        ),
    ]
